---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```


```{r}
edu_data <- read_csv("data/school_data.csv") %>% janitor::clean_names() %>% 
  column_to_rownames("x1")

head(edu_data)
```


```{r}
edu_data <- edu_data %>% 
  select(home_school, state_school)
```


```{r}
edu_data %>% 
  ggplot(aes(x = home_school,
             y = state_school))+
  geom_point()
```


scale the data
```{r}
edu_scale <- edu_data %>% 
  mutate(across(.fns = scale))

head(edu_scale, 10)
```


```{r}
edu_scale %>% 
  ggplot(aes(x = home_school,
             y = state_school))+
  geom_point()
```


```{r}
set.seed(1234)

clustered_edu <- edu_scale %>% 
  kmeans(centers = 6, # the "k" in k_means
         nstart = 25) # how many random initial configurations

clustered_edu
```


```{r}
library(broom)

clustered_edu %>% 
  tidy(col.names = colnames(edu_scale))
```
withinss (within sum of squares) = average distance between points in that cluster
we want to have a small withinss

add cluster group to original data set
```{r}
clustered_edu %>% 
  augment(edu_data)
```


```{r}
glance(clustered_edu)
```
tot.withinss (total within sum of squares) = sum(withinss)


```{r}
# set min & max number of clusters
max_k <- 20

k_clusters <- tibble(
  k = 1:max_k
)

k_clusters <- k_clusters %>% 
  mutate(
    kclust = map(k, ~ kmeans(edu_scale, .x, nstart = 25)), # .x represents "k" 
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, edu_data)
  )
```


```{r}
clusterings <- k_clusters %>% 
  unnest(glanced)

clusterings
```

elbow chart
```{r}
clusterings %>% 
  ggplot(aes(x = k,
             y = tot.withinss))+
  geom_point()+
  geom_line()+
  scale_x_continuous(breaks = seq(1, 20 , 1))
```



```{r}
library(factoextra)

fviz_nbclust(edu_scale,
             kmeans,
             method = "wss",
             nstart = 25)
```

silhouetting 
```{r}
fviz_nbclust(edu_scale,
             kmeans,
             method = "silhouette",
             nstart = 25)
```


```{r}
fviz_nbclust(edu_scale,
             kmeans,
             method = "gap_stat",
             nstart = 25)
```
we want the smallest k which is within 1 standard deviation of the highest gap statistic


```{r}
clusterings %>% 
  unnest(cols = c(augmented)) %>% 
  filter(k <= 6) %>% 
  ggplot(aes(x = home_school,
             y = state_school))+
  geom_point(aes(colour = .cluster))+
  facet_wrap(~ k)
```



