---
title: "R Notebook"
output: html_notebook
---


```{r}
as.Date("2022-08-22")
```


POSIX - Start at 1970-01-01 00:00:00

```{r}
date_time1 <- as.POSIXct("2020-01-01 00:00:00")
date_time1
```


```{r}
unclass(date_time1)
```
This returns the number of seconds that have passed between 1970-01-01
[(38 * 365) + (12 * 366)] * 24 * 60 * 60 = 1577836800


```{r}
date_time2 <- as.POSIXlt("2020-01-01 00:00:00")
date_time2
```


```{r}
unclass(date_time2)
```


```{r}
library(tidyverse)
library(lubridate)
```


```{r}
netflix <- read_csv("data/netflix.csv")
```


```{r}
ymd("2019-01-19")

mdy("January 19th, 2019")

dmy("19-Jan-2019")

ymd_hms("2019-01-19 10:08:26")

ymd_hm("2019-01-19 10:08")

ymd_h("2019-01-19 10")
```


```{r}
netflix <- netflix %>% 
  mutate(date_added = mdy(date_added))

netflix
```


## Extracting components

```{r}
netflix <- netflix %>% 
  mutate(day = day(date_added),
         month = month(date_added, label = TRUE, abbr = FALSE),
         year = year(date_added),
         week_day = wday(date_added, label = TRUE, abbr = TRUE),
         .after = date_added)
```


## Calculating time spans

`Difftime`: a _datetime_ object that represents days
`Period`: represent a timespan e.g. week/month/day
`Duration`: represent an exact number of _seconds_

```{r}
netflix <- netflix %>% 
  mutate(time_period = as.period(today() - date_added),
         time_years = as.numeric(time_period, "years"),
         time_hours = as.numeric(time_period, "hours"),
         time_minutes = as.numeric(time_period, "minutes"),
         time_seconds = as.numeric(time_period, "seconds"),
         .after = year)
```


## Subtracting periods from dates

```{r}
netflix <- netflix %>% 
  mutate(promo_date = date_added - weeks(2),
         removal_date = date_added + months(4),
         .after = date_added)
```


```{r}
netflix <- netflix %>% 
  mutate(time_duration = as.duration(today() - date_added))

netflix %>% 
  select(starts_with("time_"))
```


## Understanding timezones

```{r}
OlsonNames()
```


```{r}
OlsonNames()
ymd_hms("2023-09-13 10:22:01", tz = "Atlantic/Faeroe")
```


```{r}
netflix %>% 
  mutate(date_tz_1 = force_tz(date_added, tzone = "Asia/Singapore"),
         date_tz_2 = with_tz(date_added, tzone = "Asia/Singapore")) %>% 
  select(date_added, date_tz_1, date_tz_2)
```





