---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(infer)
```


```{r}
houses <- read_csv("data/ames.csv") %>% clean_names()
```


```{r}
houses %>% 
  ggplot(aes(x = sale_price)) +
  geom_histogram(col = "white")
```


```{r}
houses_summary <- houses %>% 
  summarise(
    mean_sale_price = mean(sale_price)
  )

houses_summary
```

```{r}
houses_sample_100 <- houses %>% 
  rep_sample_n(size = 100,
               rep = 1000,
               replace = TRUE) %>% 
  summarise(mean_sale_price = mean(sale_price))

houses_sample_100
```


```{r}
results <- houses_sample_100 %>% 
  summarise(
    lower_bound = quantile(mean_sale_price, probs = 0.05),
    upper_bound = quantile(mean_sale_price, probs = 0.95)
  )

results
```


```{r}
results <- tibble()

for (sample_num in 1:1000) {
  
  this_sample <- houses %>% 
    rep_sample_n(size = 100, reps = 1) %>% 
    ungroup() %>% 
    select(sale_price)
  
  this_bootstrap <- this_sample %>% 
    specify(response = sale_price) %>% 
    generate(reps = 1000, type = "bootstrap") %>%
    calculate(stat = "mean")
  
  this_ci <- this_bootstrap %>% 
    get_ci(level = 0.95, type = "percentile")
  
  this_results <- c(
    sample_num = sample_num,
    lower = this_ci %>% 
      pull(lower_ci),
    upper = this_ci %>% 
      pull(upper_ci)
  )
  
  results <- results %>% 
    bind_rows(this_results)
}
```

